function titleFromRequest(userText: string, fallback: string): string {
  const trimmed = userText.trim();
  if (!trimmed) {
    return fallback;
  }
  const cleaned = trimmed
    .replace(/^(?:buat(?:kan)?|generate|bikin)\s+(?:gu[ae]\s+)?(?:file\s+)?/i, "")
    .replace(/\b(yang|paling|canggih|keren|bagus)\b/gi, " ")
    .replace(/\s+/g, " ")
    .trim();
  if (cleaned.length < 3) {
    return fallback;
  }
  return cleaned.slice(0, 120);
}

export function buildMarkdownDocumentBody(input: {
  userText: string;
  priorBody: string;
  title: string;
}): string {
  if (input.priorBody.trim()) {
    return input.priorBody.slice(0, 40_000);
  }

  const intro = input.userText.trim() || "Dokumen dibuat otomatis oleh VANDOR.";

  return `# ${input.title}

${intro}

## Ringkasan

Dokumen ini dihasilkan oleh **VANDOR Document Agent** sesuai permintaan kamu.

## Isi

- Permintaan: ${intro.slice(0, 500)}
- Dibuat: ${new Date().toISOString()}
- Platform: VANDOR Multi-Agent

## Catatan

Edit isi di chat jika perlu versi lebih detail.
`.trim();
}

type SheetInput = {
  name: string;
  rows: Array<Array<string | number | boolean | null>>;
};

export function buildDefaultSpreadsheet(input: {
  userText: string;
  title: string;
}): { title: string; format: "xlsx"; sheets: SheetInput[] } {
  const request = input.userText.trim().slice(0, 240) || "Custom export";

  return {
    title: titleFromRequest(input.userText, input.title),
    format: "xlsx",
    sheets: [
      {
        name: "Dashboard",
        rows: [
          ["Metrik", "Jan", "Feb", "Mar", "Apr", "Trend"],
          ["Revenue (jt)", 120, 138, 152, 171, "↑"],
          ["Active Users", 1250, 1410, 1580, 1760, "↑"],
          ["Conversion %", 3.2, 3.6, 4.0, 4.4, "↑"],
          ["NPS", 71, 74, 77, 80, "↑"],
          ["Churn %", 2.8, 2.5, 2.3, 2.1, "↓"],
        ],
      },
      {
        name: "Breakdown",
        rows: [
          ["Kategori", "Nilai", "Target", "Status"],
          ["Produk A", 45000, 42000, "OK"],
          ["Produk B", 32000, 35000, "Watch"],
          ["Produk C", 28000, 25000, "OK"],
          ["Layanan", 19000, 20000, "Watch"],
        ],
      },
      {
        name: "Meta",
        rows: [
          ["Field", "Value"],
          ["Generated by", "VANDOR"],
          ["Request", request],
          ["Created", new Date().toISOString()],
        ],
      },
    ],
  };
}

export function inferDocumentTitle(
  userText: string,
  format: "pdf" | "xlsx" | "csv" | "docx"
): string {
  const base = titleFromRequest(userText, "VANDOR Export");
  if (format === "xlsx") {
    return base.includes("Excel") ? base : `${base} Excel`;
  }
  if (format === "docx") {
    return base.includes("Word") ? base : `${base} Document`;
  }
  if (format === "pdf") {
    return base.includes("Laporan") ? base : `Laporan ${base}`;
  }
  return base;
}
