import type { AgentDefinition } from "../core/agent-definition";
import { defineAgent } from "../core/agent-definition";
import { AGENT_TOOL_MAP } from "../core/tool-catalog";
import {
  browserAgentExecute,
  chatAgentExecute,
  codingAgentExecute,
  documentAgentExecute,
  fixAgentExecute,
  memoryAgentExecute,
  monitoringAgentExecute,
  orchestratorAgentExecute,
  plannerAgentExecute,
  stubAgentExecute,
  testingAgentExecute,
  toolAgentExecute,
} from "./executors";

/** Definisi 12 agent V2 — Fase 4: testing + fix loop (deploy = fase 5). */
export const PLATFORM_AGENT_DEFINITIONS: AgentDefinition[] = [
  defineAgent({
    id: "chat",
    name: "Chat Agent",
    description:
      "Interaksi user, intent, penjelasan hasil — tidak mengerjakan task teknis.",
    capabilities: ["conversation", "intent", "summarize", "deliver"],
    tools: AGENT_TOOL_MAP.chat,
    memoryScopes: ["conversation", "user", "short_term"],
    execute: chatAgentExecute,
  }),
  defineAgent({
    id: "planner",
    name: "Planner Agent",
    description: "Analisa permintaan, buat execution plan, tentukan agent.",
    capabilities: ["analyze", "decompose", "schedule"],
    tools: AGENT_TOOL_MAP.planner,
    memoryScopes: ["conversation", "project", "user"],
    execute: plannerAgentExecute,
  }),
  defineAgent({
    id: "orchestrator",
    name: "Orchestrator",
    description:
      "Otak workflow — routing, retry, queue, agregasi hasil. Bukan LLM.",
    capabilities: [
      "workflow",
      "retry",
      "timeout",
      "queue",
      "aggregate",
      "monitor",
    ],
    tools: AGENT_TOOL_MAP.orchestrator,
    memoryScopes: ["short_term"],
    execute: orchestratorAgentExecute,
  }),
  defineAgent({
    id: "coding",
    name: "Coding Agent",
    description: "Backend, frontend, API, refactor, bug fix, tools & skills.",
    capabilities: ["code", "refactor", "debug", "api", "database"],
    tools: AGENT_TOOL_MAP.coding,
    memoryScopes: ["project", "knowledge", "short_term"],
    execute: codingAgentExecute,
  }),
  defineAgent({
    id: "browser",
    name: "Browser Agent",
    description: "Web search, research, crawl, dokumentasi, validasi info.",
    capabilities: ["search", "research", "crawl", "validate"],
    tools: AGENT_TOOL_MAP.browser,
    memoryScopes: ["knowledge", "short_term"],
    execute: browserAgentExecute,
  }),
  defineAgent({
    id: "document",
    name: "Document Agent",
    description: "PDF, DOCX, XLSX, CSV, OCR, ringkasan & analisa dokumen.",
    capabilities: ["pdf", "docx", "xlsx", "ocr", "summarize"],
    tools: AGENT_TOOL_MAP.document,
    memoryScopes: ["project", "knowledge"],
    execute: documentAgentExecute,
  }),
  defineAgent({
    id: "memory",
    name: "Memory Agent",
    description: "Gateway memori — short/long/conversation/project/user/knowledge.",
    capabilities: ["store", "retrieve", "merge", "scope"],
    tools: AGENT_TOOL_MAP.memory,
    memoryScopes: [
      "short_term",
      "long_term",
      "conversation",
      "project",
      "user",
      "knowledge",
    ],
    execute: memoryAgentExecute,
  }),
  defineAgent({
    id: "tool",
    name: "Tool Agent",
    description: "Eksekutor integrasi: DB, API, WA, VPS, Docker, custom tools.",
    capabilities: ["integrate", "execute", "plugin"],
    tools: AGENT_TOOL_MAP.tool,
    memoryScopes: ["short_term", "user"],
    execute: toolAgentExecute,
  }),
  defineAgent({
    id: "testing",
    name: "Testing Agent",
    description: "Unit, integration, e2e, security, stress, performance tests.",
    capabilities: ["unit", "integration", "e2e", "security", "performance"],
    tools: AGENT_TOOL_MAP.testing,
    memoryScopes: ["project", "short_term"],
    execute: testingAgentExecute,
  }),
  defineAgent({
    id: "fix",
    name: "Fix Agent",
    description: "Analisa error, perbaiki, koordinasi re-test via orchestrator.",
    capabilities: ["diagnose", "patch", "verify"],
    tools: AGENT_TOOL_MAP.fix,
    memoryScopes: ["project", "knowledge"],
    execute: fixAgentExecute,
  }),
  defineAgent({
    id: "deploy",
    name: "Deployment Agent",
    description: "Docker, VPS, PM2, CI/CD, rollback, backup, health check.",
    capabilities: ["deploy", "rollback", "backup", "health"],
    tools: AGENT_TOOL_MAP.deploy,
    memoryScopes: ["project", "short_term"],
    execute: stubAgentExecute("deploy"),
  }),
  defineAgent({
    id: "monitoring",
    name: "Monitoring Agent",
    description: "CPU, RAM, token, API, error, log, workflow, queue, health.",
    capabilities: ["metrics", "logs", "alerts", "cost"],
    tools: AGENT_TOOL_MAP.monitoring,
    memoryScopes: ["short_term", "knowledge"],
    execute: monitoringAgentExecute,
  }),
];
