const UUID_FILE_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}(?:\.[a-z0-9]{1,8})?$/i;
const VAULT_AUTO_PREFIX_RE = /^vault-\d+/i;
const DEFAULT_SUMMARY_RE =
  /^(image|video|audio|document|text|code|sheet|pdf|other|file)\s*file\s*:/i;

/** Nama file otomatis (UUID.jpg, vault-123…) — bukan label user. */
export function isAutoGeneratedVaultFileName(fileName: string): boolean {
  const trimmed = fileName.trim();
  if (!trimmed) {
    return true;
  }
  return UUID_FILE_RE.test(trimmed) || VAULT_AUTO_PREFIX_RE.test(trimmed);
}

function isDefaultVaultSummary(summary: string, fileName: string): boolean {
  const s = summary.trim();
  if (!s) {
    return true;
  }
  if (DEFAULT_SUMMARY_RE.test(s)) {
    return true;
  }
  return s.includes(fileName);
}

/**
 * Label yang ditampilkan di list/kartu berangkas.
 * Prioritas: fileName (jika bukan UUID) → ringkasan user → tag pertama → fileName mentah.
 */
export function resolveVaultDisplayName(input: {
  fileName: string;
  summary: string | null;
  tags?: string[];
}): string {
  const fileName = input.fileName.trim();
  if (fileName && !isAutoGeneratedVaultFileName(fileName)) {
    return fileName;
  }

  const summary = input.summary?.trim();
  if (summary && !isDefaultVaultSummary(summary, fileName)) {
    return summary.split("\n")[0]?.trim().slice(0, 255) || fileName;
  }

  const tag = input.tags?.find((t) => t.trim());
  if (tag) {
    return tag.trim().slice(0, 255);
  }

  return fileName || "File berangkas";
}

/** Nama file saat unduh — pakai label tampilan + ekstensi asli jika perlu. */
export function vaultDownloadFileName(input: {
  fileName: string;
  summary: string | null;
  tags?: string[];
  mimeType: string;
}): string {
  const storageName = input.fileName.trim();
  const display = resolveVaultDisplayName(input);
  if (!isAutoGeneratedVaultFileName(storageName) || display === storageName) {
    return storageName;
  }
  if (/\.[a-z0-9]{1,8}$/i.test(display)) {
    return display;
  }
  const ext = storageName.match(/(\.[a-z0-9]{1,8})$/i)?.[1];
  return ext ? `${display}${ext}` : display;
}
